<?php
// Session validation
session_start();
if (!isset($_SESSION['authenticated'])) {
    header('Location: login.php');
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exhibitions List</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <header class="bg-amber-400 text-gray-200 p-4">
        <nav class="flex justify-between">
            <a href="index.php" class="text-gray-200 hover:text-gray-300">Back to Index</a>
            <span class="text-gray-200">Welcome, <?php echo $_SESSION['username']; ?></span>
            <a href="logout.php" class="text-gray-200 hover:text-gray-300">Logout</a>
        </nav>
    </header>
    <main class="p-4">
        <h1 class="text-2xl text-gray-600 mb-4">Exhibitions List</h1>
        <div class="flex justify-between mb-4">
            <button class="bg-amber-400 hover:bg-amber-500 text-gray-200 p-2 rounded" onclick="location.href='create_exhibitions.php'">Add New Item</button>
            <input type="text" id="search" class="p-2 rounded" placeholder="Search...">
        </div>
        <table id="exhibitions-table" class="w-full text-gray-600">
            <thead>
                <tr>
                    <th class="px-4 py-2">ID</th>
                    <th class="px-4 py-2">Name</th>
                    <th class="px-4 py-2">Actions</th>
                </tr>
            </thead>
            <tbody id="table-body">
                <!-- Table content will be generated by JavaScript -->
            </tbody>
        </table>
    </main>

    <script>
        // Fetch API to get exhibitions list
        fetch('../backend/exhibitions.php', {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => response.json())
        .then(data => {
            const tableBody = document.getElementById('table-body');
            data.forEach(exhibition => {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td class="px-4 py-2">${exhibition.id}</td>
                    <td class="px-4 py-2">${exhibition.name}</td>
                    <td class="px-4 py-2">
                        <a href="edit_exhibitions.php?id=${exhibition.id}" class="text-amber-400 hover:text-amber-500">Edit</a>
                        <button class="text-red-500 hover:text-red-600" onclick="deleteExhibition(${exhibition.id})">Delete</button>
                    </td>
                `;
                tableBody.appendChild(row);
            });
        });

        // Delete exhibition using AJAX
        function deleteExhibition(id) {
            fetch('../backend/exhibitions.php', {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ id: id })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    location.reload();
                } else {
                    alert('Error deleting exhibition');
                }
            });
        }

        // Search bar filtering
        const searchInput = document.getElementById('search');
        searchInput.addEventListener('input', () => {
            const filter = searchInput.value.toUpperCase();
            const rows = document.getElementById('table-body').rows;
            for (let i = 0; i < rows.length; i++) {
                const row = rows[i];
                const nameCell = row.cells[1];
                if (nameCell.textContent.toUpperCase().indexOf(filter) > -1) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            }
        });
    </script>
</body>
</html>